import type { Metadata } from "next";
import { Geist, Oswald, Poppins, Onest } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/components/LanguageProvider";

/**
 * Notlar:
 * - weight, Google Fonts’ta mevcut değerlerle eşleşmeli.
 * - display: "swap" önerilir.
 * - variable: CSS değişkeni olarak kullanacağız.
 */
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  display: "swap",
});

const onest = Onest({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  display: "swap",
  weight: ["100", "200", "400", "700", "900"],
});

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["700"], // sadece bold kullanacaksanız yeterli
  variable: "--font-oswald",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  /**
   * Poppins değişken font olsa da Google Fonts’ta
   * belirli weight kesitlerini de seçebilirsiniz.
   * Virgülle tek string yazmak yerine ayrı ayrı dizi verin.
   */
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body
        className={`${geistSans.variable} ${oswald.variable} ${poppins.variable} ${onest.variable} antialiased`}
      >
        <LanguageProvider defaultLang="tr">{children}</LanguageProvider>
      </body>
    </html>
  );
}
